### ISSUE TITLE
launch via hotkey

### ISSUE THREAD

**Issue by amosbird** [tsudoko/sumi#1]
Hi, this tool is great. I wonder if it can be used as a command line tool only, so that i can doing orc just like taking screenshot via hotkey.

**Comment by tsdko** [comment]
I can make one. What do you think about this output format?
```
detected n-character sequence
possible matches for character 1
possible matches for character 2
...
possible matches for character n
```

Example:
![image](https://sr.ht/Vsme.png)
```
|PL媒体とレコ_ド形式
|lI
PF
L
媒煤嫌煉蝶轢爆蠣燥楳
体休俸
とご
レ
コ〕]‥ヨョ
_一-ー
ド
形
式弐武
```

**Comment by amosbird** [comment]
ok  i get the idea. IMO we can just use the first line as the output and let user to do the correction by hand :)

**Comment by tsdko** [comment]
Done. By the way, if you don't care about other possible matches, you can always use `tesseract-ocr` provided by Tesseract.
